### ISSUE TITLE
Readme examples don’t console.log

### ISSUE THREAD

**Issue by rickvipond** [planarnetwork/raptor#16]
Hi

i’ve installed on Node 20 and tried the readme examples but while it spins and seems to run, nothing console logs?

**Comment by linusnorton** [comment]
Are you able to attach the gtfs file you are using?

**Comment by rickvipond** [comment]
Yes

Just the most recent ATOC GTFS (from April 2021) on this page: [https://transitfeeds.com/p/association-of-train-operating-companies/284](https://transitfeeds.com/p/association-of-train-operating-companies/284), I can't find anything newer

[Actual GTFS.zip link here:](https://transitfeeds.com/p/association-of-train-operating-companies/284/latest/download)

**Comment by linusnorton** [comment]
I used to maintain that feed but couldn't continue unfortunately. I will test it out.

**Comment by linusnorton** [comment]
There was an issue with the dependency that loads the gtfs file. Updating has fixed it. I've done a number of small upgrade and corrected a few of the examples in the README.md. Version 2.2.3 should work although you might want a more up to date gtfs file.
