### ISSUE TITLE
Examples in readme don't work in console ("gtfs.zip" should be a stream object)

### ISSUE THREAD

**Issue by reki2000** [planarnetwork/raptor#6]
Hello, this repository is very helpful to understand RAPTOR algorithm. Thanks a lot to publish this.

I'd like to report a small issue.

As I tried to run example codes in readme, but `stream.pipe is not a funtion` error occurs. 

I just corrected `"gtfs.zip"` to `fs.createReadStream("gtfs.zip")` and it works. I understand that this fix is only for running `node` from console (command-line), not from webapp. 

Maybe it's more beginner-friendly to mention about this in readme.

Thanks!

**Comment by linusnorton** [comment]
Hey, glad to hear it's been useful. I've updated the readme with that change.
